name: build and deploy
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{secrets.NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{secrets.NODE_VERSION}}

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test